# VERSION           0.0.1
# DOCKER-VERSION    0.7.3
# AUTHOR:           Alex Kestner, akestner@healthguru.com
# DESCRIPTION:      Image with docker-registry project and dependecies
# TO_BUILD:         docker build -rm -t docker_registry .
# TO_RUN:           docker run -p 5000:5000 docker_registry

FROM ubuntu:12.04

RUN sed -i 's/main$/main universe/' /etc/apt/sources.list && apt-get update
RUN apt-get install -y git-core build-essential python-dev libevent1-dev python-openssl liblzma-dev wget

RUN cd /tmp; wget http://python-distribute.org/distribute_setup.py
RUN cd /tmp; python distribute_setup.py; easy_install pip; rm distribute_setup.py

ADD . /var/www/docker-registry
ADD ./config/boto.cfg /etc/boto.cfg
ADD /root/.ssh/healthguru.docker_registry.public.pem /root/.ssh/healthguru.docker_registry.public.pem

RUN cd /var/www/docker-registry && pip install -r requirements.txt

EXPOSE <%= @port %>

CMD cd /var/www/docker-registry && ./run.sh